// vue-tailwind/src/components/Container.vue
<script lang="ts">
export type ContainerProps = { class?: ClassValue } & ContainerKlass.RootVariants;
</script>

<script setup lang="ts">
import { computed } from "vue";

import type { ClassValue } from "@klass/core";

import * as ContainerKlass from "./Container.klass";

const props = defineProps<{
  class?: ContainerProps["class"];
  center?: ContainerProps["center"];
  max?: ContainerProps["max"];
}>();

const className = computed(() => ContainerKlass.Root({ center: props.center, max: props.max }, [props.class]));
</script>

<template>
  <div :class="className">
    <slot></slot>
  </div>
</template>

// svelte-tailwind/src/components/Container.svelte
<script lang="ts" context="module">
  export type ContainerProps = { class?: ClassValue } & ContainerKlass.RootVariants;
</script>

<script lang="ts">
  import type { ClassValue } from "@klass/core";

  import * as ContainerKlass from "./Container.klass";

  export let center: ContainerProps["center"] | undefined = ContainerKlass.Root.o.defaultVariants.center;
  export let max: ContainerProps["max"] | undefined = ContainerKlass.Root.o.defaultVariants.max;

  let _class: ContainerProps["class"] = undefined;
  export { _class as class };

  let className: string = undefined;
  $: className = ContainerKlass.Root({ center, max }, [_class]);
</script>

<div {...$$restProps} class={className}>
  <slot />
</div>
