// vue-tailwind/src/components/Text.vue
<script lang="ts">
export type TextProps = { class?: ClassValue } & TextKlass.RootVariants;
</script>

<script setup lang="ts">
import { computed } from "vue";

import type { ClassValue } from "@klass/core";

import * as TextKlass from "./Text.klass";

const props = defineProps<{
  class?: TextProps["class"];
  inline?: TextProps["inline"];
  align?: TextProps["align"];
  color?: TextProps["color"];
  size?: TextProps["size"];
  weight?: TextProps["weight"];
}>();

const className = computed(() =>
  TextKlass.Root(
    {
      inline: props.inline,
      align: props.align,
      color: props.color,
      size: props.size,
      weight: props.weight,
    },
    [props.class]
  )
);
</script>

<template>
  <div :class="className">
    <slot></slot>
  </div>
</template>

// svelte-tailwind/src/components/Text.svelte
<script lang="ts" context="module">
  export type TextProps = { class?: ClassValue } & TextKlass.RootVariants;
</script>

<script lang="ts">
  import type { ClassValue } from "@klass/core";

  import * as TextKlass from "./Text.klass";

  export let inline: TextProps["inline"] | undefined = TextKlass.Root.o.defaultVariants.inline;
  export let align: TextProps["align"] | undefined = TextKlass.Root.o.defaultVariants.align;
  export let color: TextProps["color"] | undefined = TextKlass.Root.o.defaultVariants.color;
  export let size: TextProps["size"] | undefined = TextKlass.Root.o.defaultVariants.size;
  export let weight: TextProps["weight"] | undefined = TextKlass.Root.o.defaultVariants.weight;

  let _class: TextProps["class"] = undefined;
  export { _class as class };

  let className: string = undefined;
  $: className = TextKlass.Root({ inline, align, color, size, weight }, [_class]);
</script>

<div {...$$restProps} class={className}>
  <slot />
</div>
