// svelte-tailwind/src/components/Box.svelte
<script lang="ts" context="module">
  export type BoxProps = { class?: ClassValue } & BoxKlass.RootVariants;
</script>

<script lang="ts">
  import type { ClassValue } from "@klass/core";

  import * as BoxKlass from "./Box.reklass";

  export let d: BoxProps["d"] | undefined = undefined;
  export let ps: BoxProps["ps"] | undefined = undefined;
  export let t: BoxProps["t"] | undefined = undefined;
  export let r: BoxProps["r"] | undefined = undefined;
  export let b: BoxProps["b"] | undefined = undefined;
  export let l: BoxProps["l"] | undefined = undefined;
  export let m: BoxProps["m"] | undefined = undefined;
  export let mx: BoxProps["mx"] | undefined = undefined;
  export let my: BoxProps["my"] | undefined = undefined;
  export let mt: BoxProps["mt"] | undefined = undefined;
  export let mr: BoxProps["mr"] | undefined = undefined;
  export let mb: BoxProps["mb"] | undefined = undefined;
  export let ml: BoxProps["ml"] | undefined = undefined;
  export let p: BoxProps["p"] | undefined = undefined;
  export let px: BoxProps["px"] | undefined = undefined;
  export let py: BoxProps["py"] | undefined = undefined;
  export let pt: BoxProps["pt"] | undefined = undefined;
  export let pr: BoxProps["pr"] | undefined = undefined;
  export let pb: BoxProps["pb"] | undefined = undefined;
  export let pl: BoxProps["pl"] | undefined = undefined;

  let _class: BoxProps["class"] = undefined;
  export { _class as class };

  let className: string = undefined;
  $: className = BoxKlass.Root(
    {
      d,
      ps,
      t,
      r,
      b,
      l,
      m,
      mx,
      my,
      mt,
      mr,
      mb,
      ml,
      p,
      px,
      py,
      pt,
      pr,
      pb,
      pl,
    },
    [_class]
  );
</script>

<div {...$$restProps} class={className}>
  <slot />
</div>

// vue-tailwind/src/components/Box.vue
<script lang="ts">
export type BoxProps = { class?: ClassValue } & BoxKlass.RootVariants;
</script>

<script setup lang="ts">
import { computed } from "vue";

import type { ClassValue } from "@klass/core";

import * as BoxKlass from "./Box.reklass";

const props = defineProps<{
  class?: BoxProps["class"];
  d?: BoxProps["d"];
  ps?: BoxProps["ps"];
  t?: BoxProps["t"];
  r?: BoxProps["r"];
  b?: BoxProps["b"];
  l?: BoxProps["l"];
  m?: BoxProps["m"];
  mx?: BoxProps["mx"];
  my?: BoxProps["my"];
  mt?: BoxProps["mt"];
  mr?: BoxProps["mr"];
  mb?: BoxProps["mb"];
  ml?: BoxProps["ml"];
  p?: BoxProps["p"];
  px?: BoxProps["px"];
  py?: BoxProps["py"];
  pt?: BoxProps["pt"];
  pr?: BoxProps["pr"];
  pb?: BoxProps["pb"];
  pl?: BoxProps["pl"];
}>();

const className = computed(() =>
  BoxKlass.Root(
    {
      d: props.d,
      ps: props.ps,
      t: props.t,
      r: props.r,
      b: props.b,
      l: props.l,
      m: props.m,
      mx: props.mx,
      my: props.my,
      mt: props.mt,
      mr: props.mr,
      mb: props.mb,
      ml: props.ml,
      p: props.p,
      px: props.px,
      py: props.py,
      pt: props.pt,
      pr: props.pr,
      pb: props.pb,
      pl: props.pl,
    },
    [props.class]
  )
);
</script>

<template>
  <div :class="className">
    <slot></slot>
  </div>
</template>
