// qwik-tailwind/src/components/Button.tsx
import { component$, Slot } from "@builder.io/qwik";

import type { ClassValue } from "@klass/core";

import * as ButtonKlass from "./Button.klass";

type ButtonProps = { class?: ClassValue } & ButtonKlass.RootVariants;

const Button = component$<ButtonProps>(({ color, size, class: className, ...props }) => {
  return (
    <button type="button" {...props} class={ButtonKlass.Root({ color, size }, [className])}>
      <Slot />
    </button>
  );
});

export type { ButtonProps };
export default Button;

// vue-tailwind/src/components/Button.vue
<script lang="ts">
export type ButtonProps = { class?: ClassValue } & ButtonKlass.RootVariants;
</script>

<script setup lang="ts">
import { computed } from "vue";

import type { ClassValue } from "@klass/core";

import * as ButtonKlass from "./Button.klass";

const props = defineProps<{
  class?: ButtonProps["class"];
  color?: ButtonProps["color"];
  size?: ButtonProps["size"];
}>();

const className = computed(() => ButtonKlass.Root({ color: props.color, size: props.size }, [props.class]));
</script>

<template>
  <button type="button" :class="className">
    <slot></slot>
  </button>
</template>
