// qwik-tailwind/src/components/Container.tsx
import { component$, Slot } from "@builder.io/qwik";

import type { ClassValue } from "@klass/core";

import * as ContainerKlass from "./Container.klass";

type ContainerProps = { class?: ClassValue } & ContainerKlass.RootVariants;

const Container = component$<ContainerProps>(({ center, max, class: className, ...props }) => {
  return (
    <div {...props} class={ContainerKlass.Root({ center, max }, [className])}>
      <Slot />
    </div>
  );
});

export type { ContainerProps };
export default Container;

// vue-tailwind/src/components/Container.vue
<script lang="ts">
export type ContainerProps = { class?: ClassValue } & ContainerKlass.RootVariants;
</script>

<script setup lang="ts">
import { computed } from "vue";

import type { ClassValue } from "@klass/core";

import * as ContainerKlass from "./Container.klass";

const props = defineProps<{
  class?: ContainerProps["class"];
  center?: ContainerProps["center"];
  max?: ContainerProps["max"];
}>();

const className = computed(() => ContainerKlass.Root({ center: props.center, max: props.max }, [props.class]));
</script>

<template>
  <div :class="className">
    <slot></slot>
  </div>
</template>
