// fresh-tailwind/routes/_app.tsx
import type { PageProps } from "$fresh/server.ts";

export default function App({ Component }: PageProps) {
  return (
    <html data-theme="dark">
      <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>fresh-tailwind</title>
        <meta name="description" content="klass example with fresh + tailwindcss" />
        <link rel="stylesheet" href="/styles.css" />
      </head>
      <body>
        <Component />
      </body>
    </html>
  );
}

// solid-start-tailwind/src/app.tsx
// @refresh reload
import { Suspense } from "solid-js";
import { Router } from "@solidjs/router";
import { MetaProvider, Title, Meta } from "@solidjs/meta";
import { FileRoutes } from "@solidjs/start";

import "./globals.css";

export default function App() {
  return (
    <Router
      root={(props) => (
        <MetaProvider>
          <Title>solid-start-tailwind</Title>
          <Meta name="description" content="klass example with solid-start + tailwindcss" />
          <Suspense>{props.children}</Suspense>
        </MetaProvider>
      )}
    >
      <FileRoutes />
    </Router>
  );
}
